title: "German Named Entitity Recognition"
description: "This project uses data from the germeval and wikiner datasets to train a German NER model."

# Variables can be referenced across the project.yml using ${vars.var_name}
vars:
  config: "cpu_eff"
  gpu: -1
  name: "ner_german"
  version: "0.0.0"

directories:
  [
    "assets",
    "assets/spacy",
    "training",
    "configs",
    "metrics",
    "corpus",
    "packages",
  ]

assets:
  - dest: "assets/wikiner/aij-wikiner-de-wp3.bz2"
    url: "https://raw.githubusercontent.com/dice-group/FOX/master/input/Wikiner/aij-wikiner-de-wp3.bz2"
  - dest: "assets/germaner/germaner_train.tsv"
    url: "https://docs.google.com/uc?export=download&id=1Jjhbal535VVz2ap4v4r_rN1UEHTdLK5P"
  - dest: "assets/germaner/germaner_dev.tsv"
    url: "https://docs.google.com/uc?export=download&id=1ZfRcQThdtAR5PPRjIDtrVP7BtXSCUBbm"
  - dest: "assets/germaner/germaner_test.tsv"
    url: "https://docs.google.com/uc?export=download&id=1u9mb7kNJHWQCWyweMDRMuTFoOHOfeBTH"

workflows:
  all:
    - corpus
    - train
    - evaluate

commands:
  - name: corpus
    help: "Convert the data to spaCy's format"
    script:
      - "python scripts/data_prepare_wikiner.py assets/wikiner/aij-wikiner-de-wp3.bz2 assets/wikiner/iob"
      - "python scripts/data_prepare_germaner.py assets/germaner assets/germaner/iob"
      - "python -m spacy convert assets/wikiner/iob assets/spacy --n-sents 10"
      - "python -m spacy convert assets/germaner/iob assets/spacy --n-sents 10"
      - "python scripts/data_join.py assets/spacy corpus"
    deps:
      - "assets/wikiner/aij-wikiner-de-wp3.bz2"
      - "assets/germaner/germaner_train.tsv"
      - "assets/germaner/germaner_dev.tsv"
      - "assets/germaner/germaner_test.tsv"
    outputs:
      - "corpus/train.spacy"
      - "corpus/dev.spacy"
      - "corpus/test.spacy"

  - name: train
    help: "Train the full pipeline"
    script:
      - "python -m spacy train configs/${vars.config}.cfg -o training/${vars.config} --gpu-id ${vars.gpu} --paths.train corpus/train.spacy --paths.dev corpus/dev.spacy"
    deps:
      - "corpus/train.spacy"
      - "corpus/dev.spacy"
      - "configs/${vars.config}.cfg"
    outputs:
      - "training/${vars.config}/model-best"

  - name: evaluate
    help: "Evaluate on the test data and save the metrics"
    script:
      - "python -m spacy evaluate training/${vars.config}/model-best ./corpus/test.spacy --output ./metrics/${vars.config}.json --gpu-id ${vars.gpu}"
    deps:
      - "training/${vars.config}/model-best"
      - "corpus/test.spacy"
    outputs:
      - "metrics/${vars.config}.json"

  - name: visualize-model
    help: Visualize the model's output interactively using Streamlit
    script:
      - 'streamlit run scripts/visualize_model.py training/${vars.config}/model-best "Boris Franz Becker (* 22. November 1967 in Leimen) ist ein ehemaliger deutscher Tennisspieler und Olympiasieger."'
    deps:
      - training/${vars.config}/model-best

  - name: visualize-data
    help: Explore the annotated data in an interactive Streamlit app
    script:
      - "streamlit run scripts/visualize_data.py corpus/train.spacy,corpus/dev.spacy,corpus/test.spacy"
    deps:
      - "corpus/train.spacy"
      - "corpus/dev.spacy"
      - "corpus/test.spacy"

  - name: package
    help: "Package the trained model so it can be installed"
    script:
      - "python -m spacy package training/${vars.config}/model-best packages --name ${vars.name}_${vars.config} --version ${vars.version} --force"
    deps:
      - "training/${vars.config}/model-best"
    outputs_no_cache:
      - "packages/de_${vars.name}-${vars.version}/dist/de_${vars.name}_${vars.config}-${vars.version}.tar.gz"

  - name: clean
    help: "Remove intermediate files"
    script:
      - "rm -rf training/*"
      - "rm -rf metrics/*"
      - "rm -rf corpus/*"
